{"name": "test_invalid_verification", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'", "trace": "self = <allure_commons._allure.fixture object at 0x0000013EB52A1450>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n.venv\\Lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nrequest = <SubRequest 'log_on_failure' for <Function test_invalid_verification>>\n\n    @pytest.fixture()\n    def log_on_failure(request):\n        yield\n        item=request.node\n>       if item.rep_call.failed:\nE       AttributeError: 'Function' object has no attribute 'rep_call'\n\ntest_cases\\conftest.py:20: AttributeError"}, "attachments": [{"name": "VerificationFailed", "source": "9aff0d72-1117-41dc-bad3-4cb57afda6b9-attachment.png", "type": "image/png"}, {"name": "log", "source": "1c97941d-6c9c-4a9d-87e2-8a9fd5bb0976-attachment.txt", "type": "text/plain"}], "start": 1741258556753, "stop": 1741258564118, "uuid": "b3a17041-d06f-48fc-984b-cc6d739cfc12", "historyId": "3844cd87bd32c283551d35850027135e", "testCaseId": "3844cd87bd32c283551d35850027135e", "fullName": "test_admin_login.Test_01_Admin_Login#test_invalid_verification", "labels": [{"name": "tag", "value": "sanity"}, {"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "suite", "value": "test_admin_login"}, {"name": "subSuite", "value": "Test_01_Admin_Login"}, {"name": "host", "value": "Sadat"}, {"name": "thread", "value": "8448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_admin_login"}]}